version: "3.8"
services:

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - user-database
      - user-redis
    command: sh -c /app/migrations/scripts/migrations.sh

  user-database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Qwerty1234
      POSTGRES_DB: user-service
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  user-redis:
    image: redis:latest
    container_name: user_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
