version: "3.8"
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - user-database
      - user-redis
    command: sh -c /app/migrations/scripts/migrations.sh
  user-database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty1234
      MYSQL_DATABASE: user-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: Qwerty1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3308:3306
  user-redis:
    image: redis:latest
    container_name: user_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
