version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    command: sh -c ./migrations/scripts/migrations.sh
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty123
      MYSQL_DATABASE: application
      MYSQL_USER: admin
      MYSQL_PASSWORD: Qwerty123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3308:3306